[package]
name = "win"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.71.1"
cc = "1.2.32"

[lib]
crate-type = ["cdylib"]

[dependencies]
ctor = "0.2.9"
raw-window-handle = "0.6.2"
winit = { version = "0.30.8", features = ["rwh_06"] }
