name: Build everything

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-13, macos-latest] # 'macos-13' is Intel, 'macos-latest' is M1.
    runs-on: ${{ matrix.os }}
    env:
      ASAN_OPTIONS: detect_leaks=0
    steps:
      - uses: actions/checkout@v5
      - uses: inobulles/bob-action@v1
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install meson
      - name: Build
        run: |
          bob build
      - name: Set up tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 5
        with:
          limit-access-to-actor: true
          detached: true
