name: Build everything

on: [push, workflow_dispatch]

jobs:
  build_macos:
    strategy:
      matrix:
        os: [macos-13, macos-latest] # 'macos-13' is Intel, 'macos-latest' is M1.
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Bootstrap Bob the Builder
        run: |
          git clone https://github.com/inobulles/bob --depth 1 --branch v0.2.18
          cd bob
          sh bootstrap.sh
          sudo .bootstrap/bob install
      - name: Install dependencies
        run: |
          brew install meson
      - name: Build
        run: |
          bob build
      - name: Set up tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 5
        with:
          limit-access-to-actor: true
          detached: true
